### PR TITLE
fixed typescript typings

### PR DESCRIPTION
**Pull request by GenerelSchwerz**

### CODE REVIEW

**Comment by u9g** [comment]
How did this fix anything?

**Comment by GenerelSchwerz** [comment]
image

The typescript typings were invalid.

**Comment by theconezone** [comment]
Neither Prismarine-Windows or mineflayer work with typescript after the typing changes in #49. Can confirm this fixes it. I don't know enough about typescript to understand what the line was supposed to do though.

**Comment by rom1504** [comment]
typescript support will remain second class until CI is checking something

**Pull request merged**
