### PR TITLE
Export changedSlots computation to mineflayer

### PR DESCRIPTION
**Pull request by kaduvert**
move the computation for changedSlots to mineflayer and implement returning of changedSlots from clicks directly to save expensive computation

### CODE REVIEW

**Comment by rom1504** [comment]
can you explain the intent of this change? I don't understand

**Comment by kaduvert** [comment]
so returning differences between windows doesn't really belong in prismarine-windows, it does calculation which is of importance only for mineflayer because it needs to know changedSlots for the packets

i included this in https://github.com/PrismarineJS/prismarine-windows/pull/74 to get rid of version issues with mineflayer, but the behaviour is far from optimal

that's what this pr tries to adress

**Comment by kaduvert** [comment]
it also clones the inv slots by using JSON.parse(JSON.stringify(slots)) on every click, which is kind of a waste.
so i included direct returning of changedSlots from some clicks to save on this computation in some scenarios

**Comment by rom1504** [comment]
can you git depend on this in the mineflayer PR so we can see it breaks nothing?

**Comment by rom1504** [comment]
CI fails

**Comment by rom1504** [comment]
> so returning differences between windows doesn't really belong in prismarine-windows, it does calculation which is of importance only for mineflayer because it needs to know changedSlots for the packets

tbh I don't really understand this. What do you think should belong in mineflayer vs pwindows ?

**Comment by kaduvert** [comment]
currently, clicks return changedSlots directly in the format expected for minecraft packets above 1.17.
while i think returning changedSlots from acceptClick is good, returning it in a format which is intended for use in packets is not. that's mineflayer's job.

it currently returns:
```js
[{location: i, item: Item.toNotch(window.slots[i])}, ...]
```
but i think more appropriate would be:
```js
[i, ...]
```
and then to let mineflayer handle the serialization for the packets

**Pull request merged**
