### PR TITLE
Return changed slots array

### PR DESCRIPTION
**Pull request by nickelpro**
Necessary for 1.17 support @u9g

### CODE REVIEW

**Comment by u9g** [comment]
let's wait till this is working in mineflayer pr then we can merge

**Comment by nickelpro** [comment]
The 1.17 PR is now mature in it's usage of this return variable and unlikely to change, this is ready for review/merge

**Review by u9g — APPROVED** [review]
LGTM

**Review by rom1504 — CHANGES_REQUESTED** [review]
please add what's returned in docs

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
