### PR TITLE
Remove internal api from public api doc

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
doesn't mineflayer use that?

**Comment by u9g** [comment]
internally we do.

**Comment by rom1504** [comment]
if a method of pwindows is used by another package and we think it's good, then it should stay exposed

**Comment by u9g** [comment]
> if a method of pwindows is used by another package and we think it's good, then it should stay exposed

what do you mean if we think it’s good. it’s of no value to anyone except mineflayer internally

**Comment by rom1504** [comment]
> it’s of no value to anyone except mineflayer internally

the same could be said for the whole prismarine-windows

**Pull request closed without merging**
